<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.14.0" />
    <PackageReference Include="MathNet.Numerics" Version="5.0.0" />
    <PackageReference Include="MathNet.Numerics.MKL.Win-x64" Version="3.0.0" />
    <PackageReference Include="MathNet.Numerics.Providers.OpenBLAS" Version="5.0.0" />
    <PackageReference Include="MathNet.Numerics.OpenBLAS.Win" Version="0.3.0-beta1" />
  </ItemGroup>

</Project>
